name: MassacrersMods
main: me.massacrer.mymods.MassacrersMod
version: 1.1
author: Massacrer
commands:
  mm:
    aliases: [ m, mmod ]
    description: Massacrer's private / custom mod
    usage: |
      /<command> skin | a - sets the player's armour piece (specified by the next argument) to the item number specified